### ISSUE TITLE
what to do after bazel build

### ISSUE THREAD

**Issue by DaisyMeng** [georgeliaw/rules_wheel#4]
I followed the steps, and added the following to BUILD.bazel. bazel build successful. what is the next step? i think i should see a setup.py?
```
bdist_wheel(
    name = "sample_wheel",
    srcs = glob(
        ["**"],
        exclude = ["**/*.pyc"],
    ),
    include_package_data = True
)

**Comment by georgeliaw** [comment]
@DaisyMeng the rule generates a `.whl` package which you should see as an output. there's an internal `setup.py` file that's written and used for packaging the wheel
